name: Terraform-test-plan-apply
on:
  push:
    branches:
      - master
  pull_request: null
permissions:
  contents: read
env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSRIPTION_ID: ${{ secrets.AZURE_SUBSRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
jobs:
  terraform-test:
    name: Terraform-test
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt
      - name: Terraform Validate
        run: terraform validate
  terraform-plan:
        name: Terraform-plan
        runs-on: ubuntu-latest
        environment: production
        needs: terraform-test
        defaults:
          run:
            shell: bash
        steps:      
        - name: Checkout
          uses: actions/checkout@v4
        - name: Login via Azure ClI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        - name: Terraform Init
          run: terraform init
        - name: Terraform Format
          run: terraform fmt -check
        - name: Terraform Plan
          run: terraform plan -input=false
        - name: Terraform Apply
          if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false
        - name: Save Terraform Plan as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: terraform-plan
            path: tfplan.binary
  terraform-apply:
        name: Terraform-Apply
        runs-on: ubuntu-latest
        needs: terraform-plan
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.5.6
          - name: Terraform Init
            run: terraform init
          - name: Download Terraform Plan Artifact
            uses: actions/download-artifact@v3
            with:
              name: terraform-plan
          - name: Terraform Apply
            run: terraform apply -auto-approve tfplan.binary
